
camel:
  starter:
    code:
      contextName: camel-starter-code

      mq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        vhost: /
        useSsl: false
        redeliveryBaseDelaySec: 15
        redeliveryMultiplier: 2
        redeliveryMaxDelaySec: 2000



